//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeSerivice
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Blood { get; set; }
        public string Country { get; set; }
        public string CStates { get; set; }
        public string City { get; set; }
        public Nullable<long> Pincode { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> PhoneNumber { get; set; }
        public string District { get; set; }
    }
}
